version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  
  # postgres:
  #   container_name: postgres-container
  #   image: postgres:13
  #   environment:
  #         POSTGRES_DB: clean-node-api
  #         POSTGRES_USER: 'root'
  #         POSTGRES_PASSWORD: "root!"
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres/data/db:/var/lib/postgresql/data 
  #   networks:
  #     - postgres-compose-network

  # pgAdmin:
  #   image: dpage/pgadmin4
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: "nil.nilson@gmail.com"
  #       PGADMIN_DEFAULT_PASSWORD: "root!"
  #   ports:
  #       - "16543:80"
  #   depends_on:
  #       - postgres
  #   networks:
  #       - postgres-compose-network

  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug" 
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050" 
      - "9222:9222"
    links:
      - mongo
  
# networks: 
#   postgres-compose-network:
#     driver: bridge

git log --pretty=format:'%C(blue) %h %C(red) %d(white) %s - %cn, %cr'